name: 'global_economic_tracker'
version: '1.0'
config-version: 2

profile: 'global_economic_tracker'

model-paths: ["models"]
test-paths: ["tests"]


models:
  global_economic_tracker:
    +materialized: table